// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProHotel.API.Migrations
{
    [DbContext(typeof(ProHotelAPIContext))]
    [Migration("20260930220713_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProHotel.Modelos.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCliente"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("numeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("idCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("ProHotel.Modelos.Consumo", b =>
                {
                    b.Property<int>("idConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consumo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConsumo"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("fechaConsumo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_consumo");

                    b.Property<int>("idDetalleReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_reserva");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    b.Property<decimal>("precioUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("idConsumo");

                    b.HasIndex("idDetalleReserva");

                    b.HasIndex("idServicio");

                    b.ToTable("consumos");
                });

            modelBuilder.Entity("ProHotel.Modelos.DetalleReserva", b =>
                {
                    b.Property<int>("IdDetalleReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleReserva"));

                    b.Property<decimal>("PrecioNochePactado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_noche_pactado");

                    b.Property<int>("idHabitacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_habitacion");

                    b.Property<int>("idReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    b.HasKey("IdDetalleReserva");

                    b.HasIndex("idHabitacion");

                    b.HasIndex("idReserva");

                    b.ToTable("detalles_reserva");
                });

            modelBuilder.Entity("ProHotel.Modelos.Empleado", b =>
                {
                    b.Property<int>("idEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEmpleado"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cargo");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("idEmpleado");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("ProHotel.Modelos.Habitacion", b =>
                {
                    b.Property<int>("idHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_habitacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHabitacion"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("idTipoHabitacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_habitacion");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<int>("piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("idHabitacion");

                    b.HasIndex("idTipoHabitacion");

                    b.ToTable("habitaciones");
                });

            modelBuilder.Entity("ProHotel.Modelos.Pago", b =>
                {
                    b.Property<int>("idPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPago"));

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("idReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    b.Property<string>("metodoPago")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("monto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("referenciaTransaccion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("referencia_transaccion");

                    b.HasKey("idPago");

                    b.HasIndex("idReserva");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("ProHotel.Modelos.Reserva", b =>
                {
                    b.Property<int>("idReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idReserva"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaCheckIn")
                        .HasColumnType("date")
                        .HasColumnName("fecha_check_in");

                    b.Property<DateTime>("fechaCheckOut")
                        .HasColumnType("date")
                        .HasColumnName("fecha_check_out");

                    b.Property<DateTime>("fechaReserva")
                        .HasColumnType("date")
                        .HasColumnName("fecha_reserva");

                    b.Property<int>("idCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("idEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("montoTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("idReserva");

                    b.HasIndex("idCliente");

                    b.HasIndex("idEmpleado");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("ProHotel.Modelos.Servicio", b =>
                {
                    b.Property<int>("idServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idServicio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("idServicio");

                    b.ToTable("servicios");
                });

            modelBuilder.Entity("ProHotel.Modelos.TipoHabitacion", b =>
                {
                    b.Property<int>("idTipoHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_habitacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoHabitacion"));

                    b.Property<int>("capacidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_personas");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("precioBaseNoche")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_base_noche");

                    b.HasKey("idTipoHabitacion");

                    b.ToTable("tipos_habitacion");
                });

            modelBuilder.Entity("ProHotel.Modelos.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuario"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("idEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("idUsuario");

                    b.HasIndex("idEmpleado");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ProHotel.Modelos.Consumo", b =>
                {
                    b.HasOne("ProHotel.Modelos.DetalleReserva", "DetalleReserva")
                        .WithMany("Consumos")
                        .HasForeignKey("idDetalleReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProHotel.Modelos.Servicio", "Servicio")
                        .WithMany("Consumos")
                        .HasForeignKey("idServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleReserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ProHotel.Modelos.DetalleReserva", b =>
                {
                    b.HasOne("ProHotel.Modelos.Habitacion", "Habitacion")
                        .WithMany("DetallesReserva")
                        .HasForeignKey("idHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProHotel.Modelos.Reserva", "Reserva")
                        .WithMany("DetallesReserva")
                        .HasForeignKey("idReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ProHotel.Modelos.Habitacion", b =>
                {
                    b.HasOne("ProHotel.Modelos.TipoHabitacion", "TipoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("idTipoHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("ProHotel.Modelos.Pago", b =>
                {
                    b.HasOne("ProHotel.Modelos.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("idReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ProHotel.Modelos.Reserva", b =>
                {
                    b.HasOne("ProHotel.Modelos.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProHotel.Modelos.Empleado", "Empleado")
                        .WithMany("Reservas")
                        .HasForeignKey("idEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ProHotel.Modelos.Usuario", b =>
                {
                    b.HasOne("ProHotel.Modelos.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("idEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ProHotel.Modelos.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProHotel.Modelos.DetalleReserva", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("ProHotel.Modelos.Empleado", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProHotel.Modelos.Habitacion", b =>
                {
                    b.Navigation("DetallesReserva");
                });

            modelBuilder.Entity("ProHotel.Modelos.Reserva", b =>
                {
                    b.Navigation("DetallesReserva");
                });

            modelBuilder.Entity("ProHotel.Modelos.Servicio", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("ProHotel.Modelos.TipoHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
